
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from './Header/Header'
import Footer from './Footer/Footer'
import store from './Redux/store'
import ReduxProvider from './Redux/Provider'
import SideMenu from './Aside/SideMenu'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='wrapper'>
          <ReduxProvider>
            <Header />
            <SideMenu />
            <main>{children}</main>
            <Footer />  
          </ReduxProvider>
        </div>
      </body>
    </html>
  )
}
